package com.rustedwax.app.detect

import com.rustedwax.app.hive.HiveScrobblePayload
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Phase 4 decision D4 flipped the default to `song`, so these tests carry more
 * weight than most: an over-claimed kind is permanent on-chain, and the
 * blocklist is the only thing standing between "default to music" and a
 * tutorial in the music index.
 */
class MusicClassifierTest {

	private fun kindOf(
		title: String,
		channel: String? = null,
		durationMs: Long? = 4 * 60 * 1000L,
		siteSaysMusic: Boolean = false,
		category: String? = null,
		isShort: Boolean = false,
		mbMatch: Boolean = false,
		autoGenerated: Boolean = false,
		ytMusic: Boolean = false,
		nativeYouTubeMusic: Boolean = false,
		youtubeMusicPodcastEpisode: Boolean = false,
		nativeGenre: String? = null,
	) = MusicClassifier
		.classify(
			title, channel, durationMs, siteSaysMusic, category, isShort, mbMatch, autoGenerated,
			ytMusic, nativeYouTubeMusic, youtubeMusicPodcastEpisode, nativeGenre,
		)
		.kind

	private val song = HiveScrobblePayload.KIND_SONG
	private val video = HiveScrobblePayload.KIND_VIDEO

	@Test
	fun `native YouTube Music is strong music context below hard format evidence`() {
		assertEquals(song, kindOf("A Clean Track", "Artist", nativeYouTubeMusic = true))
		assertEquals(
			video,
			kindOf("Episode 42 - A Conversation", "A Show", nativeYouTubeMusic = true),
		)
		assertEquals(
			video,
			kindOf(
				"A Clean Episode Title",
				"A Show",
				nativeYouTubeMusic = true,
				youtubeMusicPodcastEpisode = true,
			),
		)
		assertEquals(
			video,
			kindOf(
				"A Clean Episode Title",
				"A Show",
				nativeYouTubeMusic = true,
				nativeGenre = "Podcast",
			),
		)
	}

	/** The bug this phase exists to fix. */
	@Test
	fun `the reported guitar cover is music`() {
		assertEquals(
			song,
			kindOf(
				"【Bring Me The Horizon】I Used to Make Out With Medusa " +
					"(Instrumental) 2023【Guitar Cover】＋Screen Tabs",
				"OLD MOON CHILD",
			),
		)
	}

	@Test
	fun `covers live takes and lyric videos are all music`() {
		assertEquals(song, kindOf("Creep (Acoustic Cover)", "Some Person"))
		assertEquals(song, kindOf("Bohemian Rhapsody - Live at Wembley", "QueenOfficial"))
		assertEquals(song, kindOf("Duality (Lyrics)", "LyricChannel"))
		assertEquals(song, kindOf("Toxicity — Drum Cover", "Drummer Dan"))
	}

	@Test
	fun `youtube's Music category wins when the format rules don't object`() {
		assertEquals(song, kindOf("Some Sunday Upload", "Chan", category = "Music"))
		// A VEVO suffix is vocabulary-tier; the uploader's Gaming category outranks it.
		assertEquals(video, kindOf("Anything", "SomeVEVO", category = "Gaming"))
	}

	/**
	 * Field data 2026-07-24 evening: the category is wrong in BOTH directions.
	 * "How to Throat Sing like in DUNE!" (a tutorial) and a Manson news
	 * bulletin are both categorized Music by their uploaders. Format evidence
	 * in the title now outranks the category.
	 */
	@Test
	fun `format evidence beats a Music category`() {
		assertEquals(video, kindOf(
			"How to Throat Sing like in DUNE!", "Brandon Acker", category = "Music"))
		assertEquals(video, kindOf(
			"Marilyn Manson Releases Heavy New Single ‘Front Toward Enemy’ " +
				"Ahead of Upcoming Album",
			"Rock Celebrities", category = "Music", durationMs = 47_000L))
		// The reverse rescue: hard music evidence beats a non-music category —
		// an instrument cover filed under Education is still that song.
		assertEquals(song, kindOf(
			"Duality (Drum Cover)", "Some Academy", category = "Education"))
	}

	@Test
	fun `the blocklist keeps non-music out`() {
		assertEquals(video, kindOf("How to fix a sink", "DIY Channel"))
		assertEquals(video, kindOf("Guitar Tutorial - Beginner Chords", "GuitarLessons"))
		assertEquals(video, kindOf("Episode 42: the interview", "Some Show"))
		assertEquals(video, kindOf("Cyberpunk 2077 Review", "Reviewer"))
	}

	/**
	 * Blocklist runs before the positive signals on purpose — otherwise the
	 * word "guitar" in "Guitar Tutorial" rescues it as music.
	 */
	@Test
	fun `blocklist beats a music-sounding word in the same title`() {
		assertEquals(video, kindOf("Bass Cover Tutorial", "Teacher"))
	}

	@Test
	fun `channel blocklist only applies to the channel`() {
		// "News" in a song title must not *block* it — with positive evidence
		// it's a song; without, it falls to the plain default, not the blocklist.
		assertEquals(song, kindOf("Bad News", "Some Band", mbMatch = true))
		assertEquals("no music evidence",
			MusicClassifier.classify("Bad News", "Some Band", 4 * 60 * 1000L, false).reason)
		// …but a news channel is not a band.
		assertEquals(video, kindOf("Bad News", "BBC News"))
	}

	@Test
	fun `long form with no music signal is a video`() {
		assertEquals(
			video,
			kindOf("Three hours of something", "Chan", durationMs = 3 * 60 * 60 * 1000L),
		)
		// …but long *and* musical stays music: DJ sets and full albums are long.
		assertEquals(
			song,
			kindOf("Full Album - Greatest Hits", "Band", durationMs = 3 * 60 * 60 * 1000L),
		)
	}

	/**
	 * D4 revised in v0.5.1: two days of field data showed every default-song
	 * hit was a news clip, movie scene or vlog. With category, MusicBrainz and
	 * the vocabulary layers supplying the positive path for real music, the
	 * last-resort default is now video.
	 */
	@Test
	fun `no evidence at all defaults to video`() {
		val r = MusicClassifier.classify(
			"Some upload with no signals at all", "A Channel", 4 * 60 * 1000L, false)
		assertEquals(video, r.kind)
		assertEquals("no music evidence", r.reason)
	}

	/**
	 * The 2026-07-24 field sample: eleven film clips, trailers and shorts that
	 * went on-chain as `song`. Titles, channels and categories are the real
	 * values fetched from each video's watch page. Every one must be `video`.
	 */
	@Test
	fun `the field sample of misclassified film content is video`() {
		// Film & Animation — the category alone must decide these.
		assertEquals(video, kindOf(
			"COYOTE VS. ACME Official Final Trailer (2026) John Cena",
			"ONE Media", category = "Film & Animation"))
		assertEquals(video, kindOf(
			"THE END OF OAK STREET Official Final Trailer (2026)",
			"ONE Media", category = "Film & Animation"))
		assertEquals(video, kindOf(
			"Top Movie Scene | Giant Spider Attack | Kong: Skull Island",
			"VISIONREEL PRODUCTIONS", category = "Film & Animation"))
		assertEquals(video, kindOf(
			"You Don't Like Real Girls | Blade Runner 2049 [Open Matte]",
			"Natalizio Filmes", category = "Film & Animation"))
		// Ambiguous categories — known-but-not-music demands explicit evidence,
		// and a pipe or dash in the title is not explicit evidence.
		assertEquals(video, kindOf(
			"You and who? | 🎬 Notting Hill (1999)",
			"Universal Pictures", category = "Entertainment"))
		assertEquals(video, kindOf(
			"The weapon is meant as a gift -- It is a Crysknife  | DUNE 2021 |",
			"Groovy Movie Dog", category = "Entertainment"))
		assertEquals(video, kindOf(
			"Gsxr1000r police chase x Rolling in the deep",
			"Awahys", category = "Entertainment"))
		assertEquals(video, kindOf(
			"The surgeon (Short Film)",
			"AidAVisioN", category = "People & Blogs"))
		assertEquals(video, kindOf(
			"Connie Doherty - Showreel",
			"Connie Doherty", category = "People & Blogs"))
		assertEquals(video, kindOf(
			"Cozy Kitchen Ghibli Vibes💖",
			"Cozy Minamy", category = "People & Blogs"))
		assertEquals(video, kindOf(
			"One of the Coldest Scenes in Western Movies - \"How good are ya\"",
			"Cinema Crunch", category = "People & Blogs", isShort = true))
	}

	/** The same sample with enrichment OFF — the structural fallbacks. */
	@Test
	fun `the field sample degrades sanely without a category`() {
		// "Official Final Trailer" slipped past the exact phrase "official
		// trailer"; the structural rule reads context + trailer.
		assertEquals(video, kindOf(
			"COYOTE VS. ACME Official Final Trailer (2026) John Cena", "ONE Media"))
		// Clip channels advertise themselves in the name.
		assertEquals(video, kindOf("Some scene compilation", "Movie Trailers Source"))
		assertEquals(video, kindOf("Some scene compilation", "Cinema Crunch"))
		assertEquals(video, kindOf("Random clip", "Universal Pictures"))
		// Film vocabulary in the title.
		assertEquals(video, kindOf(
			"Top Movie Scene | Giant Spider Attack | Kong: Skull Island", "Somebody"))
		assertEquals(video, kindOf("The surgeon (Short Film)", "AidAVisioN"))
		assertEquals(video, kindOf("Connie Doherty - Showreel", "Connie Doherty"))
	}

	/**
	 * An ambiguous category requires explicit evidence — but explicit evidence
	 * does win. Fan-uploaded covers commonly sit in Entertainment or People &
	 * Blogs, and they must not be lost to the stricter rule.
	 */
	@Test
	fun `explicit music evidence overrules an ambiguous category`() {
		assertEquals(song, kindOf(
			"Creep (Acoustic Cover)", "Some Person", category = "Entertainment"))
		assertEquals(song, kindOf(
			"Duality (Lyrics)", "LyricChannel", category = "People & Blogs"))
		assertEquals(song, kindOf(
			"Anything at all", "Radiohead - Topic", category = "Entertainment"))
	}

	/**
	 * Shorts are browsed by the dozen and titled like clip captions, so weak
	 * evidence (a dash, the bare default) is not accepted for them.
	 */
	@Test
	fun `shorts need explicit music evidence`() {
		assertEquals(video, kindOf("Epic Moment - Best Scene Ever", "Clips", isShort = true))
		assertEquals(video, kindOf("Some random caption", "Uploader", isShort = true))
		// Explicit evidence still qualifies a short as music.
		assertEquals(song, kindOf("Zombie 【Guitar Cover】", "OLD MOON CHILD", isShort = true))
		// Same bar for anything under 90 seconds, shorts URL or not.
		assertEquals(video, kindOf("Funny Dog - Compilation", "Dogs", durationMs = 45_000L))
		assertEquals(song, kindOf("Riff (Official Audio)", "Band", durationMs = 45_000L))
	}

	/**
	 * The reported false positive. "Cover" as a bare substring used to force
	 * song; a magazine cover is not a music cover.
	 */
	@Test
	fun `a magazine cover is not a music cover`() {
		assertEquals(
			video,
			kindOf(
				"President Trump Says His Time Magazine Cover Photo Is 'Super Bad'",
				"Some News Outlet",
			),
		)
	}

	@Test
	fun `other non-musical cover contexts are videos`() {
		assertEquals(video, kindOf("Album Cover Art Reveal", "Design Channel"))
		assertEquals(video, kindOf("How I Shot the Cover Photo", "Photographer"))
		assertEquals(video, kindOf("Undercover Boss - Full Episode", "TV Network"))
	}

	/** The genuine covers must still read as music after the tightening. */
	@Test
	fun `real music covers still classify as song`() {
		assertEquals(song, kindOf("Creep (Acoustic Cover)", "Some Person"))
		assertEquals(song, kindOf("Toxicity — Drum Cover", "Drummer Dan"))
		assertEquals(song, kindOf("Wonderwall - Cover by Jane Doe", "Jane Doe"))
		assertEquals(song, kindOf("My cover of Zombie", "Singer"))
		assertEquals(song, kindOf("Nothing Else Matters 【Guitar Cover】", "OLD MOON CHILD"))
	}

	/**
	 * Real songs whose titles contain commentary/format words. Under the
	 * video-by-default ladder they need *positive* evidence to land as song —
	 * a category, a MusicBrainz match, or music vocabulary. That's the
	 * documented trade: the safety net moved from "default to song" to
	 * "MusicBrainz knows the recording".
	 */
	@Test
	fun `real songs with ambiguous words are rescued by positive evidence`() {
		assertEquals(song, kindOf("Chain Reaction", "Diana Ross", mbMatch = true))
		assertEquals(song, kindOf("Chain Reaction", "Diana Ross", category = "Music"))
		assertEquals(song, kindOf("Trailer Trash (Official Video)", "Modest Mouse"))
		assertEquals(song, kindOf("Hearing Damage", "Thom Yorke", mbMatch = true))
		// Without any positive evidence they fall to video — the accepted cost.
		assertEquals(video, kindOf("Chain Reaction", "Diana Ross"))
	}

	/**
	 * The sitcom compilation that showed "song" until its Comedy category
	 * arrived: "Season 6 Ep 19" wasn't recognized offline, and the ` - ` then
	 * read as an artist separator. Episode numbering must decide it with no
	 * category at all — this is the verdict that stands when the id is lost.
	 */
	@Test
	fun `episode numbering is a video even offline`() {
		assertEquals(video, kindOf(
			"The Big Bang Theory Season 6 Ep 19 - Best Scenes", "XxGanishxX"))
		assertEquals(video, kindOf("Breaking Bad S02E05 - Full Recap", "Clips4U"))
		assertEquals(video, kindOf("The Office Season 3 Episode 12", "SomeFan"))
		// …and with the category present the verdict is the same, not fought over.
		assertEquals(video, kindOf(
			"The Big Bang Theory Season 6 Ep 19 - Best Scenes", "XxGanishxX",
			category = "Comedy"))
	}

	/**
	 * "EP" is a release format in music — "EP 2" names real records. Episode
	 * matching requires the season context or the SxxExx shape, so music EPs
	 * fall through to the music evidence they carry.
	 */
	@Test
	fun `music EPs are not TV episodes`() {
		assertEquals(song, kindOf("Bloom EP (Full Album)", "Some Band"))
		assertEquals(song, kindOf("Whirlwind EP 2 (Official Audio)", "Some Band"))
	}

	/**
	 * Game-soundtrack vocabulary, from the scrobble.life maintainer's database.
	 *
	 * Calum Bowen's *Poinpy* and *Pikuniku* ship tracks literally named
	 * "Tutorial", "Tutorial (Puzzle)", "Trailer 2" and "Trailer 3"; Future has
	 * a recording called "Fukk A Interview". Every one hit the hard blocklist
	 * and was demoted to `video` even from a Topic channel with a MusicBrainz
	 * match, because the blocklist outranked both.
	 */
	@Test
	fun `soundtrack tracks on a Topic channel are music despite their titles`() {
		assertEquals(song, kindOf("Tutorial", "Calum Bowen - Topic"))
		assertEquals(song, kindOf("Tutorial (Puzzle)", "Calum Bowen - Topic"))
		assertEquals(song, kindOf("Trailer 2", "Calum Bowen - Topic"))
		assertEquals(song, kindOf("Trailer 3", "Calum Bowen - Topic"))
		assertEquals(song, kindOf("Fukk A Interview", "Future - Topic"))
		// "Wake Up" never hit a rule — it was already correct, and stays so.
		assertEquals(song, kindOf("Wake Up", "Calum Bowen - Topic"))
	}

	/**
	 * A Topic channel is generated by YouTube from a distributor feed, so its
	 * title is catalogue metadata, not a human description. That outranks even
	 * a non-music category.
	 */
	@Test
	fun `Topic provenance outranks the category and the blocklist`() {
		assertEquals(song, kindOf("Tutorial", "Calum Bowen - Topic", category = "Gaming"))
		assertEquals(
			song,
			kindOf("Provided track", "Some Artist", autoGenerated = true, category = "Education"),
		)
	}

	/**
	 * Without that provenance the same words still mean what they usually mean
	 * — a soundtrack rescue must not become a loophole for real tutorials.
	 */
	@Test
	fun `the same words still demote ordinary uploads`() {
		assertEquals(video, kindOf("Guitar Tutorial - Beginner Chords", "GuitarLessons"))
		assertEquals(video, kindOf("Trailer 2", "Movie Trailers Source"))
		assertEquals(video, kindOf("Full Interview with the director", "Some Channel"))
		// …but MusicBrainz can still rescue a real recording without a Topic channel.
		assertEquals(song, kindOf("Fukk A Interview", "FutureVEVO", mbMatch = true))
	}

	/**
	 * VEVO is deliberately *not* promoted with Topic. Artist channels host
	 * interviews, behind-the-scenes and tour trailers, so trusting them the
	 * same way would turn those into songs.
	 */
	@Test
	fun `VEVO is not treated as auto-generated provenance`() {
		assertEquals(video, kindOf("Metallica Interview 2023", "MetallicaVEVO"))
	}

	/**
	 * Field case 2026-07-28: `Blade II | Sewers of the Damned | ClipZone:
	 * Heroes & Villains` was scrobbled as a song because the first `|` made
	 * the weakest rule of all fire, yielding artist "Blade II". A three-part
	 * title is a clip caption, not `Artist - Track`.
	 */
	@Test
	fun `a three-part clip caption does not read as an artist`() {
		assertEquals(
			video,
			kindOf(
				"Blade II | Sewers of the Damned | ClipZone: Heroes & Villains",
				"ClipZone: Heroes & Villains",
			),
		)
		assertEquals(
			video,
			kindOf(
				"Blade II | Blade Fights Nomak | ClipZone: Heroes & Villains",
				"ClipZone: Heroes & Villains",
			),
		)
		// A plain two-part Artist - Track is untouched.
		assertEquals(song, kindOf("Korn - Thoughtless", "SomeUploader"))
	}

	/** The actual non-music formats those words describe are caught outright. */
	@Test
	fun `reaction videos trailers and hearings are still videos`() {
		assertEquals(video, kindOf("My Reaction Video to the Finale", "Reactor"))
		assertEquals(video, kindOf("Reacts to the new trailer", "Streamer"))
		assertEquals(video, kindOf("Dune Part Two - Official Trailer", "Warner Bros"))
		assertEquals(video, kindOf("Senate Hearing on AI - Full", "C-SPAN"))
		// Bare "reaction" is contextual: it loses to MusicBrainz/category but
		// beats a pipe-split title that merely looks like Artist - Track.
		assertEquals(video, kindOf(
			"Marilyn Manson \"Exit Wound\" REACTION | Old School Fan Hears " +
				"Chapter 2 First Single.",
			"Some Reactor", durationMs = 11 * 60 * 1000L))
	}

	/**
	 * "playthrough" is gaming as often as it is music, so it now needs an
	 * instrument qualifier — the same rule as "cover".
	 */
	@Test
	fun `playthrough needs an instrument to count as music`() {
		assertEquals(video, kindOf("Elden Ring Playthrough Part 1", "Gamer"))
		assertEquals(song, kindOf("Master of Puppets - Guitar Playthrough", "Guitarist"))
		assertEquals(song, kindOf("Enter Sandman 【Drum Playthrough】", "Drummer"))
	}

	/**
	 * Broadcast 2026-07-24T17:35 as `video`: a 42-second performance clip of
	 * a real song, whose only offline signal was the weak artist-separator
	 * shape the short-form rule refuses. A MusicBrainz confirmation is
	 * explicit evidence, so it rescues exactly this case.
	 */
	@Test
	fun `a MusicBrainz match rescues a short performance clip`() {
		assertEquals(video, kindOf("Maphra - Doomed", durationMs = 42_000L))
		assertEquals(song, kindOf("Maphra - Doomed", durationMs = 42_000L, mbMatch = true))
		// It also overrules an ambiguous category…
		assertEquals(song, kindOf(
			"Some Artist - Some Song", category = "Entertainment", mbMatch = true))
		// …but never the blocklist: kind is about the video, not the song it
		// contains, and a trailer scoring a real song is still a trailer.
		assertEquals(video, kindOf(
			"MOVIE Official Trailer (2026)", category = null, mbMatch = true))
	}

	/**
	 * Broadcast 2026-07-24T17:27 as `song` on the D4 default: the video id
	 * (and with it the Education category) was lost by finalize time, and
	 * nothing else fired. The uploader-declared #shorts tag is evidence that
	 * survives losing the URL.
	 */
	@Test
	fun `a #shorts tag in the title is short-form even with no url evidence`() {
		assertEquals(video, kindOf(
			"Kya Yajooj Majooj Ki Deewar Abhi Bhi Mojood Hai? #shorts",
			"Times Cover", durationMs = 2 * 60 * 1000L))
		// Explicit music evidence still wins for a tagged short.
		assertEquals(song, kindOf("Riff (Guitar Cover) #shorts", "Someone"))
	}

	/**
	 * Word boundaries: a music word buried inside a larger word is not a match.
	 * "discover" is not "cover"; "preview" is not "review".
	 */
	@Test
	fun `does not match music or block words inside larger words`() {
		// "discover" must not trip the cover rule — it falls to the default,
		// crucially not *because* of "cover".
		assertEquals("no music evidence",
			MusicClassifier.classify("Discover Weekly", "A Channel", 4 * 60 * 1000L, false, null).reason)
		// "preview" must not trip the "review" blocklist — the default fires,
		// not the blocklist.
		assertEquals("no music evidence",
			MusicClassifier.classify("World Premiere Preview", "A Band", 4 * 60 * 1000L, false, null).reason)
	}

	// region episode numbering

	/**
	 * Both went on-chain as `kind: song` on 2026-07-30. `EPISODE_STRUCTURAL`
	 * matched `Season 6 Ep 19` and `S06E19` but not the `NxNN` notation TV clip
	 * channels actually use.
	 */
	@Test
	fun `NxNN episode numbering reads as a TV episode`() {
		assertEquals(
			video,
			kindOf(
				"Dead City (new scene) 3x1 Maggie & Negan talk to each other " +
					"about the stabbing!",
				"The Walking Dead",
			),
		)
		assertEquals(
			video,
			kindOf(
				"The Walking Dead 11x24 Negan and Maggie talk, Maggie can't " +
					"forgive Negan - Rest In Peace",
				"Some Channel",
			),
		)
	}

	/** The spelled-out forms must keep working. */
	@Test
	fun `the existing episode forms still match`() {
		assertEquals(video, kindOf("Sitcom Scenes - Season 6 Ep 19", "Clips"))
		assertEquals(video, kindOf("Some Show S06E19 best bits", "Clips"))
	}

	/**
	 * A resolution has too many digits to be mistaken for a season, and aspect
	 * ratios are named explicitly — both otherwise have the exact shape of
	 * episode numbering.
	 */
	@Test
	fun `resolutions and aspect ratios are not episodes`() {
		assertEquals(song, kindOf("Korn - Trash 1920x1080", "KornVEVO"))
		assertEquals(song, kindOf("Korn - Trash (640x480)", "KornVEVO"))
		assertEquals(song, kindOf("Korn - Trash 16x9", "KornVEVO"))
		assertEquals(song, kindOf("Korn - Trash 4x3", "KornVEVO"))
	}

	/** `EP 2` is a release format, and that exemption is untouched. */
	@Test
	fun `a bare EP number is still not an episode`() {
		assertEquals(song, kindOf("Some Artist - EP 2", "Some Channel"))
	}
	// endregion

	// region the YouTube Music catalogue
	//
	// Adapted from the desktop extension. Keyed by video id, so it answers where
	// a string-matched MusicBrainz lookup returns nothing — which in field
	// testing was most Spanish-language and small-channel uploads.

	@Test
	fun `the catalogue rescues a song no heuristic would recognise`() {
		// "Para Mis Soldados" on a personal channel: no separator the parser
		// trusts, no category, nothing in MusicBrainz.
		assertEquals(video, kindOf("Tocan la Puerta", "El Kid"))
		assertEquals(song, kindOf("Tocan la Puerta", "El Kid", ytMusic = true))
	}

	@Test
	fun `the catalogue outranks an ambiguous category`() {
		assertEquals(
			song,
			kindOf("Some Track", "Some Channel", category = "People & Blogs", ytMusic = true),
		)
	}

	/**
	 * Positive-only, and it must stay below the format blocklist: a reaction
	 * video that picks up a user-generated audio match is still a video.
	 */
	@Test
	fun `the catalogue does not rescue a format the blocklist caught`() {
		assertEquals(video, kindOf("Song X — reaction video", "Some Channel", ytMusic = true))
		assertEquals(
			video,
			kindOf("THE THING Official Trailer", "ONE Media", ytMusic = true),
		)
	}

	/** Absence is not evidence against music, so nothing changes without it. */
	@Test
	fun `no catalogue entry leaves the other rules alone`() {
		assertEquals(song, kindOf("Korn - Trash", "KornVEVO", ytMusic = false))
	}
	// endregion

	// region long-form gates
	//
	// The mirror of the short-form rule, at the other end, and both thresholds
	// are the extension's. RustedWax had only a lower bound, so a 45-minute
	// podcast titled "Host - Guest" reached the weak "title names an artist"
	// rule and became a song.

	@Test
	fun `a long podcast with a dash in the title is not a song`() {
		assertEquals(
			video,
			kindOf("Lex Fridman - Conversation with Someone", "Some Channel",
				durationMs = 45 * 60 * 1000L),
		)
	}

	@Test
	fun `a medium-form clip needs a positive music signal`() {
		assertEquals(
			video,
			kindOf("Jimmy Fallon - Interviewing A Guest", "Late Night",
				durationMs = 10 * 60 * 1000L),
		)
	}

	/** Real long-form music always carries a signal, and those are checked first. */
	@Test
	fun `long-form music with a real signal still passes`() {
		assertEquals(
			song,
			kindOf("Some Artist - Greatest Hits (Full Album)", "Some Channel",
				durationMs = 50 * 60 * 1000L),
		)
		assertEquals(
			song,
			kindOf("DJ Someone - Summer Set", "Some Channel",
				durationMs = 60 * 60 * 1000L, ytMusic = true),
		)
		assertEquals(
			song,
			kindOf("Radiohead - Live at Glastonbury", "Some Channel",
				durationMs = 90 * 60 * 1000L),
		)
	}

	/** An ordinary-length video is untouched by either gate. */
	@Test
	fun `the middle of the range is unaffected`() {
		assertEquals(song, kindOf("Korn - Trash", "Some Channel", durationMs = 4 * 60 * 1000L))
	}
	// endregion

	// region hashtag-only titles

	/**
	 * On-chain 2026-07-29: `katter — #guitar #dubstep #djdubstep #fnaf
	 * #fivenightsatfreddy`, `kind: song`, on the strength of `category=Music`
	 * alone. The category was arguably right about the content and still
	 * produced a permanent playlist entry naming no track.
	 */
	@Test
	fun `a title of nothing but hashtags is not a song`() {
		assertEquals(
			video,
			kindOf(
				"#guitar #dubstep #djdubstep #fnaf #fivenightsatfreddy",
				"katter",
				durationMs = 30_000L,
				category = "Music",
			),
		)
		assertEquals(
			video,
			kindOf("#plena#panama 🇵🇦", "Rony González", durationMs = 52_000L, category = "Music"),
		)
	}

	@Test
	fun `hashtag-only outranks the category but not real provenance`() {
		// A distributor feed's title is catalogue metadata and never looks like
		// this, so provenance still wins if it somehow does.
		assertEquals(
			song,
			kindOf("#guitar #dubstep", "Some Artist - Topic", category = "Music"),
		)
		assertEquals(
			song,
			kindOf("#guitar #dubstep", "Some Artist", category = "Music", autoGenerated = true),
		)
	}

	/** A real title with tags appended keeps its kind — only the tags go. */
	@Test
	fun `tags appended to a real title do not change the kind`() {
		assertEquals(
			song,
			kindOf(
				"🏫Un reggaeton educativo #insulini #reggaeton #perreo #poliglota",
				"insulini",
				durationMs = 60_000L,
				category = "Music",
			),
		)
	}
	// endregion

	@Test
	fun `KoWNsyNVR28 movie edit structure outranks bare Music category`() {
		assertEquals(
			video,
			kindOf(
				"Just how many superpowers does he have? #movie #foryou #edit #funny",
				"Mias_edit",
				durationMs = 137_181,
				category = "Music",
				isShort = true,
			),
		)
	}

	@Test
	fun `ordinary movie words and real music provenance remain songs`() {
		assertEquals(song, kindOf("Artist - Movie Star (Official Music Video)", category = "Music"))
		assertEquals(song, kindOf("The Movie Song", category = "Music"))
		assertEquals(
			song,
			kindOf("Movie Edit #movie #edit", "Artist - Topic", category = "Music"),
		)
		assertEquals(
			song,
			kindOf("Movie Edit #movie #edit", "Artist", category = "Music", autoGenerated = true),
		)
		assertEquals(
			song,
			kindOf("Movie Edit #movie #edit", "Artist", category = "Music", ytMusic = true),
		)
		assertEquals(
			song,
			kindOf("Movie Edit #movie #edit", "Artist", category = "Music", mbMatch = true),
		)
	}

	@Test
	fun `Te Bote hard catalogue provenance outranks generic movie in channel`() {
		assertEquals(
			song,
			kindOf(
				"Casper, Nio García, Darell, Nicky Jam, Bad Bunny, Ozuna - " +
					"Te Bote Remix (Video Oficial)",
				"Flow La Movie",
				durationMs = 422_461,
				category = "Music",
				ytMusic = true,
			),
		)
		assertEquals(song, kindOf("Recording", "Flow La Movie", mbMatch = true))
	}

	@Test
	fun `generic movie channel still vetoes weak category evidence`() {
		assertEquals(
			video,
			kindOf("Unproven upload", "Example Movie Channel", category = "Music"),
		)
	}
}
