package com.rustedwax.app.enrich

import android.content.Context
import org.json.JSONObject
import java.io.File

/**
 * On-disk cache of resolved video facts, keyed by video id.
 *
 * Two reasons it isn't optional. The 160% double-listen broadcasts two
 * transactions for one track and would otherwise fetch the page twice, and the
 * Now-tab preview wants facts without being allowed to touch the network. A
 * video's category and credits don't change, so entries never expire — they're
 * only evicted to keep the directory small.
 *
 * **Every field the classifier or the rules read must round-trip.** Until
 * v0.8.0 `autoGenerated` was written by the parser and then silently dropped
 * here, so a cache hit downgraded a distributor-fed Art Track to whatever the
 * title heuristics made of it — and the 2026-07-29 session took 22 cache hits.
 * `lengthSeconds` has the same requirement and a sharper edge: it gates the
 * short-clip floor, so losing it on a cache hit would silently re-impose the
 * 30-second minimum.
 */
class FactsCache(context: Context, private val maxEntries: Int = 200) {

	private val dir = File(context.filesDir, "enrich").apply { mkdirs() }

	/**
	 * Memory front for the disk store. Exists so the Now-tab preview — which
	 * re-renders every second — can ask for facts without touching disk after
	 * the first hit.
	 */
	private val memory = java.util.concurrent.ConcurrentHashMap<String, VideoFacts>()

	fun get(videoId: String): VideoFacts? {
		memory[videoId]?.let { return it }
		val file = fileFor(videoId) ?: return null
		if (!file.exists()) return null
		return runCatching {
			val o = JSONObject(file.readText())
			// v0.8.6 inferred watch-page provenance from lengthSeconds, but a
			// YouTube Music fallback can supply that field too. An old entry cannot
			// answer which source resolved, so force one fresh lookup instead of
			// silently promoting fallback metadata to watch-page proof.
			if (!o.has("watchPageResolved")) return@runCatching null
			VideoFacts(
				videoId = videoId,
				title = o.optStringOrNull("title"),
				author = o.optStringOrNull("author"),
				category = o.optStringOrNull("category"),
				lengthSeconds = o.optLong("lengthSeconds").takeIf { it > 0 },
				// Absent stays null, so a pre-v0.8.1 cache entry written without
				// these fields fails the short-clip gate rather than inheriting a
				// silent "public". Those entries simply get the 30s floor until
					// the page is fetched again.
				isUnlisted = o.optBooleanOrNull("isUnlisted"),
				isCrawlable = o.optBooleanOrNull("isCrawlable"),
				watchPageResolved = o.optBoolean("watchPageResolved"),
				originalArtist = o.optStringOrNull("originalArtist"),
				originalTitle = o.optStringOrNull("originalTitle"),
				autoGenerated = o.optBoolean("autoGenerated"),
				musicVideoType = o.optStringOrNull("musicVideoType"),
				album = o.optStringOrNull("album"),
			)
		}.getOrNull()?.also { memory[it.videoId] = it }
	}

	fun put(facts: VideoFacts) {
		memory[facts.videoId] = facts
		val file = fileFor(facts.videoId) ?: return
		runCatching {
			val o = JSONObject()
				.putOpt("title", facts.title)
				.putOpt("author", facts.author)
				.putOpt("category", facts.category)
				.putOpt("lengthSeconds", facts.lengthSeconds)
					.putOpt("isUnlisted", facts.isUnlisted)
					.putOpt("isCrawlable", facts.isCrawlable)
					.put("watchPageResolved", facts.watchPageResolved)
				.putOpt("originalArtist", facts.originalArtist)
				.putOpt("originalTitle", facts.originalTitle)
				.put("autoGenerated", facts.autoGenerated)
				.putOpt("musicVideoType", facts.musicVideoType)
				.putOpt("album", facts.album)
			file.writeText(o.toString())
			evictIfNeeded()
		}
	}

	/**
	 * Video ids are `[A-Za-z0-9_-]{11}`, but this builds a file path, so it is
	 * validated rather than trusted — an id arriving from a scraped address bar
	 * has no business containing a path separator.
	 */
	private fun fileFor(videoId: String): File? =
		if (VIDEO_ID.matches(videoId)) File(dir, "$videoId.json") else null

	private fun evictIfNeeded() {
		val files = dir.listFiles() ?: return
		if (files.size <= maxEntries) return
		files.sortedBy { it.lastModified() }
			.take(files.size - maxEntries)
			.forEach { it.delete() }
	}

	private fun JSONObject.optStringOrNull(key: String): String? =
		if (isNull(key)) null else optString(key).ifBlank { null }

	/** Distinguishes "false" from "was never written", which the gate cares about. */
	private fun JSONObject.optBooleanOrNull(key: String): Boolean? =
		if (has(key) && !isNull(key)) optBoolean(key) else null

	private companion object {
		val VIDEO_ID = Regex("""[A-Za-z0-9_-]{11}""")
	}
}
