package com.rustedwax.app.enrich

/**
 * What a resolver managed to learn about a video beyond what the media session
 * said.
 *
 * Every field is optional and every field is advisory. Enrichment runs on a
 * budget against markup nobody promised us, so the pipeline must produce a
 * correct scrobble with this object absent, empty, or only half filled in.
 */
data class VideoFacts(
	val videoId: String,
	/** The real video title, free of whatever the page passed to MediaSession. */
	val title: String? = null,
	/** The uploading channel. */
	val author: String? = null,
	/** YouTube's own category — "Music", "Gaming", "Entertainment"… */
	val category: String? = null,
	/**
	 * The video's real length, from whichever resolver supplied it.
	 *
	 * Two jobs. It is the fallback when the media session publishes no
	 * `DURATION` — a 2026-07-29 shorts session lost 10 clips that way, skipped
	 * as "no duration" before any rule could look at them. YouTube Music can
	 * also supply this field, so its presence must never be used as proof that
	 * the separate watch-page request succeeded.
	 */
	val lengthSeconds: Long? = null,
	/** True only when the watch-page parser found a `videoDetails` object. */
	val watchPageResolved: Boolean = false,
	/**
	 * `microformat.playerMicroformatRenderer.isUnlisted` — the video is not
	 * publicly listed, so it can only be reached by direct link.
	 *
	 * This is the ad guard, and it was found the hard way. v0.8.0 gated the
	 * short-clip floor on the watch page merely *resolving*, on the assumption
	 * that ad creatives have no public watch page. They do. A 2026-07-29 Chrome
	 * session put `Video ad upload channel — Blurry: Formula única` on-chain: it
	 * was served at `m.youtube.com/shorts/CYgQQqvwwsY`, a genuine `/shorts/`
	 * URL, and its page resolved with `category=People & Blogs`, so both halves
	 * of the proof were satisfied.
	 *
	 * Fetching that page next to a real short from the same feed showed what
	 * actually separates them:
	 *
	 * | field | ad | real short |
	 * | --- | --- | --- |
	 * | `isUnlisted` | true | false |
	 * | `isCrawlable` | false | true |
	 * | `viewCount` | 1 | 96229 |
	 *
	 * `isUnlisted` is the one to use. An ad creative is unlisted by
	 * construction; a short reached by scrolling the feed is public by
	 * construction. It is also structural rather than a name match — the channel
	 * was literally called "Video ad upload channel", but that is a string
	 * YouTube can rename or localize.
	 *
	 * **Null means the field was absent**, which is treated as "not proven
	 * public" rather than as `false`. Reading absence as public is precisely the
	 * direction that lets an ad through, so if YouTube renames this field the
	 * short-clip floor closes rather than silently re-opening the leak.
	 */
	val isUnlisted: Boolean? = null,
	/**
	 * `videoDetails.isCrawlable`. Corroborates [isUnlisted] — false on the ad,
	 * true on the real short — but not relied on alone, since a legitimately
	 * unindexed upload is a thing that happens and being uncrawlable says
	 * nothing about being an advertisement. Carried for the log, not for the gate.
	 */
	val isCrawlable: Boolean? = null,
	/** Artist credited in the description, for covers and live takes. */
	val originalArtist: String? = null,
	/** Song credited in the description, when it differs from the video title. */
	val originalTitle: String? = null,
	/**
	 * The release, from the line after the `Song · Artist` credit on an
	 * auto-generated description.
	 *
	 * `album` has been a field on [com.rustedwax.app.hive.HiveScrobblePayload]
	 * since Phase 0 and nothing ever populated it — every RustedWax entry went
	 * on-chain without one. The desktop extension has been reading it out of the
	 * same three-line block all along (`parseYtVideoDescription`), so this is
	 * catching up rather than inventing anything.
	 */
	val album: String? = null,
	/**
	 * The description opens with "Provided to YouTube by …", which only
	 * appears on distributor-fed Art Tracks. Proof the upload is a catalogue
	 * recording rather than a human-authored video, so the classifier trusts
	 * it above every title heuristic.
	 */
	val autoGenerated: Boolean = false,
	/**
	 * `videoDetails.musicVideoType` from YouTube Music, when it has a record.
	 *
	 * Adapted from the desktop extension, which uses it as its authoritative
	 * music signal. Keyed by video id rather than by a parsed artist/track pair,
	 * so it answers where MusicBrainz returns `no match` — which in field
	 * testing was most Spanish-language and small-channel uploads.
	 *
	 * Read positive-only. See [YouTubeMusicParser.Result.recognisedAsMusic].
	 */
	val musicVideoType: String? = null,
) {
	val isEmpty: Boolean
		get() = title == null && author == null && category == null &&
			lengthSeconds == null && originalArtist == null &&
			originalTitle == null && !autoGenerated && musicVideoType == null &&
			!watchPageResolved

	/**
	 * YouTube Music holds this video as music. Podcast-episode membership is
	 * deliberately excluded; see [YouTubeMusicParser.Result.recognisedAsMusic].
	 */
	val recognisedByYouTubeMusic: Boolean
		get() = YouTubeMusicParser.isRecognisedMusicType(musicVideoType)

	/**
	 * The watch page returned a well-formed `videoDetails` for this id.
	 *
	 * An existence proof, not metadata — but on its own it proved too little.
	 * See [isUnlisted]; [provenPublicVideo] is the gate the rules use. Kept
	 * separate so the log can tell "the page never resolved" apart from "the page
	 * resolved and said unlisted", which are very different diagnoses.
	 */
	val resolvedOnWatchPage: Boolean get() = watchPageResolved

	/**
	 * The id names a real, publicly listed video.
	 *
	 * The condition for the lowered short-clip floor. Both halves are load
	 * bearing: without the first an unresolvable id would qualify, and without
	 * the second an ad creative does — which is exactly what happened.
	 *
	 * `isUnlisted == false` rather than `!isUnlisted`, so an absent field
	 * (null) fails the gate instead of passing it.
	 */
	val provenPublicVideo: Boolean get() = resolvedOnWatchPage && isUnlisted == false
}

/**
 * Resolves extra facts about a video.
 *
 * An interface for one reason: the shipping implementation scrapes an
 * undocumented blob out of the watch page (decision D8) and can break whenever
 * YouTube reskins. When it does, a Data-API implementation drops in here
 * without the pipeline noticing.
 */
interface MetadataResolver {
	/** Null when nothing could be learned. Never throws. */
	suspend fun resolve(videoId: String): VideoFacts?
}
