package com.rustedwax.app.enrich

import org.json.JSONObject

/**
 * Pulls facts out of a YouTube watch page. Pure — no network, no Android.
 *
 * Separated from [YouTubePageResolver] deliberately. This is the part decision
 * D8 called fragile, so it is also the part that has to be testable without a
 * device: a checked-in page fixture turns "YouTube changed its markup" from a
 * silent production regression into a failing unit test.
 */
object WatchPageParser {

	/**
	 * Pulls one `var name = {…};` object out of the page by matching braces.
	 *
	 * Brace counting rather than a regex because the object is megabytes of
	 * nested JSON containing every bracket character there is, and it is
	 * followed on the same line by more script. Quote- and escape-aware, or the
	 * first `}` inside a description would truncate it.
	 */
	fun extractJson(html: String, name: String): String? {
		val marker = html.indexOf(name)
		if (marker < 0) return null
		val start = html.indexOf('{', marker)
		if (start < 0) return null

		var depth = 0
		var inString = false
		var escaped = false
		for (i in start until html.length) {
			val c = html[i]
			when {
				escaped -> escaped = false
				c == '\\' && inString -> escaped = true
				c == '"' -> inString = !inString
				inString -> Unit
				c == '{' -> depth++
				c == '}' -> {
					depth--
					if (depth == 0) return html.substring(start, i + 1)
				}
			}
		}
		return null
	}

	/** @throws org.json.JSONException if the blob isn't the shape we expect */
	fun parsePlayerResponse(videoId: String, json: String): VideoFacts {
		val root = JSONObject(json)
		val details = root.optJSONObject("videoDetails")
		val micro = root.optJSONObject("microformat")
			?.optJSONObject("playerMicroformatRenderer")

		val description = details?.optString("shortDescription").orEmpty()
		val credits = mineDescription(description)

		return VideoFacts(
			videoId = videoId,
			title = details?.optString("title")?.ifBlank { null },
			author = details?.optString("author")?.ifBlank { null },
			ownerHandle = OwnerHandle.fromOwnerProfileUrl(
				micro?.optString("ownerProfileUrl")?.ifBlank { null },
			),
			category = micro?.optString("category")?.ifBlank { null },
			lengthSeconds = details?.optString("lengthSeconds")
				?.toLongOrNull()?.takeIf { it > 0 },
			watchPageResolved = details != null,
			// Null when the field is absent, not false. Absence must not read as
			// "public" — that is the direction that lets an ad through, and D8
			// requires breakage to be distinguishable from absence.
			isUnlisted = micro?.takeIf { it.has("isUnlisted") }?.optBoolean("isUnlisted"),
			isCrawlable = details?.takeIf { it.has("isCrawlable") }?.optBoolean("isCrawlable"),
			originalArtist = credits?.first,
			originalTitle = credits?.second,
			autoGenerated = AUTO_GENERATED.containsMatchIn(description),
			album = mineAlbum(description),
		)
	}

	/**
	 * The release name from an auto-generated description.
	 *
	 * Those descriptions have a fixed three-part shape, which is the only reason
	 * this is safe to read at all:
	 *
	 * ```
	 * Provided to YouTube by <distributor>
	 *
	 * <Song> · <Artist> · <more artists>
	 *
	 * <Album>
	 *
	 * ℗ <year> <label>
	 * ```
	 *
	 * Adapted from the extension's `parseYtVideoDescription`, which takes the
	 * album from the line after the credit line. Restricted to descriptions
	 * carrying the `Provided to YouTube by` header — on a hand-written
	 * description the line after any credit is prose, and inventing an album from
	 * prose would write nonsense to a chain that can't be edited.
	 */
	fun mineAlbum(description: String): String? {
		if (!AUTO_GENERATED.containsMatchIn(description)) return null
		val lines = description.lines().map { it.trim() }.filter { it.isNotEmpty() }
		// The credit line is the one carrying the `·` separators.
		val creditIndex = lines.indexOfFirst { it.contains(AUTO_SEPARATOR) }
		if (creditIndex < 0) return null
		return lines.getOrNull(creditIndex + 1)
			// The ℗/© line follows the album when a video has no album at all.
			?.takeUnless { RIGHTS_LINE.containsMatchIn(it) }
			?.takeIf { it.length <= 120 }
	}

	/**
	 * Looks for the original artist in the description. Returns
	 * `artist to title`, either of which may be null.
	 *
	 * Two shapes are worth the trouble. Auto-generated Topic descriptions open
	 * with `Provided to YouTube by …` and then `Song · Artist`. Cover uploads
	 * are hand-written and tend to credit the original in a line of its own.
	 *
	 * Everything else is left alone: guessing an artist out of free prose would
	 * write confident nonsense to a chain that can't be edited.
	 */
	fun mineDescription(description: String): Pair<String?, String?>? {
		if (description.isBlank()) return null

		AUTO_CREDIT.find(description)?.let { m ->
			val song = m.groupValues[1].trim().ifEmpty { null }
			val artist = m.groupValues[2].trim().ifEmpty { null }
			if (artist != null) return artist to song
		}
		ORIGINAL_ARTIST_AND_TITLE.find(description)?.let { m ->
			val artist = m.groupValues[1].trim().ifEmpty { null }
			val song = m.groupValues[2].trim().ifEmpty { null }
			if (artist != null) return artist to song
		}
		for (pattern in ORIGINAL_ARTIST_ONLY) {
			pattern.find(description)?.let { m ->
				val artist = m.groupValues[1].trim().trim('"', '\'', '.', '-', '–').trim()
				if (artist.isNotEmpty() && artist.length <= 60) return artist to null
			}
		}
		return null
	}

	/**
	 * Marks a distributor-fed Art Track. YouTube writes this header itself on
	 * uploads delivered through a music distributor, so it is proof the title
	 * is catalogue metadata rather than a human-authored video description —
	 * which is exactly what the classifier's title heuristics assume.
	 *
	 * Broader than checking for a `- Topic` channel name, because Official
	 * Artist Channels absorb their Art Tracks and lose the suffix while
	 * keeping this header.
	 */
	private val AUTO_GENERATED =
		Regex("""Provided to YouTube by""", RegexOption.IGNORE_CASE)

	/** The interpunct that separates fields on an auto-generated credit line. */
	private const val AUTO_SEPARATOR = " · "

	/**
	 * The `℗ 2019 Label` / `© …` line. It sits directly after the credits when a
	 * track has no album, so without this the copyright notice becomes the album.
	 */
	private val RIGHTS_LINE = Regex("""^[℗©]\s*(?:19|20)\d{2}\b|^(?:℗|©)""")

	/** `Song · Artist` under a `Provided to YouTube by …` header. */
	private val AUTO_CREDIT = Regex(
		"""Provided to YouTube by[^\n]*\n+([^\n·]+)·([^\n·]+)""",
		RegexOption.IGNORE_CASE,
	)

	/** `Original: Artist - Title`, `Song: Artist – Title`. */
	private val ORIGINAL_ARTIST_AND_TITLE = Regex(
		"""(?:^|\n)[ \t]*(?:original song|original|song)[ \t]*[:\-][ \t]*""" +
			"""([^\n\-–]{1,60}?)[ \t]*[\-–][ \t]*([^\n]{1,80})""",
		RegexOption.IGNORE_CASE,
	)

	private val ORIGINAL_ARTIST_ONLY = listOf(
		Regex("""original (?:song |track )?by[ \t]+([^\n,.(]{1,60})""", RegexOption.IGNORE_CASE),
		Regex("""originally by[ \t]+([^\n,.(]{1,60})""", RegexOption.IGNORE_CASE),
		Regex("""(?:^|\n)[ \t]*artist[ \t]*[:\-][ \t]*([^\n]{1,60})""", RegexOption.IGNORE_CASE),
		Regex("""(?:^|\n)[ \t]*band[ \t]*[:\-][ \t]*([^\n]{1,60})""", RegexOption.IGNORE_CASE),
	)
}
