package com.rustedwax.app.detect

import com.rustedwax.app.enrich.MusicBrainzVerifier
import com.rustedwax.app.enrich.VideoFacts
import com.rustedwax.app.hive.HiveScrobblePayload

/**
 * Turns an observed media session into the payload the extension would have
 * broadcast.
 *
 * Kind selection moved to [MusicClassifier] in Phase 4. PHASE0 locked in
 * "`video` for youtube.com, `song` only for music.youtube.com", which turned
 * out to under-claim music badly — covers, live takes and lyric videos are
 * music that doesn't look like `Artist - Track`. Decision D4 inverts the
 * default; see PHASE4.md.
 */
object ScrobbleBuilder {

	/**
	 * The artist/track the payload would carry, before MusicBrainz has its
	 * say. Public because the engine needs exactly this pair to *ask*
	 * MusicBrainz, and the two computations must never drift apart.
	 */
	fun creditsOf(session: SessionSnapshot, facts: VideoFacts? = null): Parsed? {
		val rawTitle = facts?.title ?: session.title ?: return null
		val channel = facts?.author ?: session.artist
		val parsed = TitleParser.parse(rawTitle, channel)
		// A description credit beats a parsed one: on a cover it names the
		// original artist, which is the whole point of looking.
		return Parsed(
			artist = facts?.originalArtist ?: parsed.artist,
			track = facts?.originalTitle?.let { TitleParser.clean(it) } ?: parsed.track,
		)
	}

	data class Parsed(val artist: String?, val track: String)

	/** Null when the session isn't broadcastable — the caller shows why. */
	/**
	 * @param videoId the id to build `url` from. Defaults to the session's own
	 * confirmed id; the engine passes a search-resolved one when the address
	 * bar never named the video.
	 */
	fun from(
		session: SessionSnapshot,
		facts: VideoFacts? = null,
		mb: MusicBrainzVerifier.Match? = null,
		videoId: String? = session.confirmed?.videoId,
	): HiveScrobblePayload? {
		if (!session.payloadViable) return null
		val sessionTitle = session.title ?: return null
		val duration = session.durationMs ?: return null

		// Enrichment's title is the video's real one; the media session's can be
		// whatever the page chose to publish.
		val rawTitle = facts?.title ?: sessionTitle
		val channel = facts?.author ?: session.artist

		val siteSaysMusic = when (val id = session.identity) {
			is YouTubeProbe.Identity.Confirmed -> id.isMusic
			is YouTubeProbe.Identity.SiteOnly -> id.isMusic
			else -> false
		}

		// Classified before parsing: cleaning strips "cover", "live" and
		// "lyrics", which are the strongest music signals there are.
		val kind = MusicClassifier.classify(
			rawTitle = rawTitle,
			channel = channel,
			durationMs = duration,
			siteSaysMusic = siteSaysMusic,
			enrichedCategory = facts?.category,
			isShort = session.confirmed?.isShort == true,
			musicbrainzMatch = mb?.found == true,
			autoGenerated = facts?.autoGenerated == true,
		)

		val credits = creditsOf(session, facts) ?: return null
		// A MusicBrainz confirmation supplies the canonical spelling, so this
		// entry lines up with every other scrobble of the same recording.
		val artist = if (mb?.found == true) mb.artist ?: credits.artist else credits.artist
		val title = if (mb?.found == true) mb.title ?: credits.track else credits.track

		return HiveScrobblePayload(
			kind = kind.kind,
			title = title,
			artist = artist,
			timestamp = HiveScrobblePayload.isoTimestamp(session.trackStartedAtEpochSec),
			duration = HiveScrobblePayload.formatDuration(duration / 1000),
			percentPlayed = session.percentPlayed
				?.let { (it * 100).toInt().coerceIn(0, 100) },
			platform = "youtube",
			url = videoId?.let { "https://www.youtube.com/watch?v=$it" },
		)
	}

	/**
	 * Why the kind came out the way it did, for the diagnostics card. Uses the
	 * same inputs as [from], so the preview and the broadcast can't disagree —
	 * an earlier version dropped `siteSaysMusic` and `isShort` here, and the
	 * card showed a different verdict than the one that went on-chain.
	 */
	fun kindReason(
		session: SessionSnapshot,
		facts: VideoFacts? = null,
		mb: MusicBrainzVerifier.Match? = null,
	): String? {
		val title = facts?.title ?: session.title ?: return null
		val siteSaysMusic = when (val id = session.identity) {
			is YouTubeProbe.Identity.Confirmed -> id.isMusic
			is YouTubeProbe.Identity.SiteOnly -> id.isMusic
			else -> false
		}
		return MusicClassifier.classify(
			rawTitle = title,
			channel = facts?.author ?: session.artist,
			durationMs = session.durationMs,
			siteSaysMusic = siteSaysMusic,
			enrichedCategory = facts?.category,
			isShort = session.confirmed?.isShort == true,
			musicbrainzMatch = mb?.found == true,
			autoGenerated = facts?.autoGenerated == true,
		).reason
	}

	/**
	 * A fixed payload for exercising signing and broadcast without playback.
	 * Marked plainly so it's obvious on-chain that it came from a test.
	 */
	fun testPayload(): HiveScrobblePayload = HiveScrobblePayload(
		kind = HiveScrobblePayload.KIND_VIDEO,
		title = "RustedWax Mobile test scrobble",
		artist = "RustedWax Mobile",
		timestamp = HiveScrobblePayload.isoTimestamp(System.currentTimeMillis() / 1000),
		duration = "0:30",
		percentPlayed = 100,
		platform = "test",
	)
}
